version: "3"

services:

  tornado_websocket :
    build: ws_detection
    container_name: tornado_websocket
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./ws_detection/:/src
    ports:
      - "7000-7100:7000-7100"
    command:
      "sh ./launch_tornado_metric.sh"

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    ports:
      - "6379"

networks:
  default:
      name: dd_network